# docker-compose.yml
services:
  analytics:
    ports:
      - 4000:4000
    env_file:
      - .env
    build: .
    depends_on:
      - redis
    networks:
      - my-awesome-network

  redis:
    image: redis:8.2.2-alpine
    ports:
      - "6379:6379"
    networks:
      - my-awesome-network

networks:
  my-awesome-network:
    driver: bridge
